version: "3"

services:
  app:
    image: ghcr.io/piotrb/codespaces-base:main-minimal

    init: true
    # privileged: true

    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/app

    entrypoint: /usr/local/share/docker-init.sh
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
